server:
    error:
        include-message: always
        include-binding-errors: always


spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/register-server
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostGreSQLDialect
        properties:
            hibernate:
                format_sql: true
            show-sql: true